### ISSUE TITLE
Change the pip package call name to something without dash

### ISSUE THREAD

**Issue by LilleAndersen** [janw/letterboxd-watchlist-rss#7]
Having dash between the words confuses windows and docker when trying to call the  script

**Comment by janw** [comment]
Can you elaborate and show some examples of where that confusion occurs?

**Comment by LilleAndersen** [comment]
Error 1:
>>> letterboxd-rss
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'letterboxd' is not defined

I get this error from windows running the command in python3.12

Seems to me that the dash is causing the issue.

Also got the error in chronos in a docker container. https://github.com/simse/chronos 

Error 2:
Traceback (most recent call last):
  File "/chronos/scripts/letterboxd/letterboxd.py", line 1, in <module>
    letterboxd-rss
NameError: name 'letterboxd' is not defined

I have gotten it to work in linux python virtual environment.

**Comment by janw** [comment]
I don't know chronos but it looks like you are trying to run `letterboxd-rss` as a command in a python script. That will not work because that's not valid python syntax.

You may have to put

```python
from letterboxd_rss.__main__ import main

main(
  # your arguments here
)
```

in the script but I cannot support this specific use-case.

The dash in the name is not an issue here, thus I'm closing this.
